name:                rounded-hw
version:             0.1.0.0
github:              "minoki/rounded-hw"
license:             BSD3
author:              "ARATA Mizuki"
maintainer:          "minorinoki@gmail.com"
copyright:           "2019 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md
- cbits/rounded-common.inl
- cbits/rounded-avx512.inl

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/minoki/rounded-hw#readme>

dependencies:
- base >= 4.7 && < 5
- integer-logarithms
- deepseq
- vector
- primitive
- array
# - rounded

flags:
  pure-hs:
    description: Disable FFI
    manual: true
    default: false

  c99:
    description: "Restrict use of platform-dependent features (e.g. SSE2) and only use C99"
    manual: true
    default: false

  avx512:
    description: "Use AVX512"
    manual: true
    default: false

  ghc-prim:
    description: "Use GHC's \"foreign import prim\""
    manual: true
    default: true

  x87-long-double:
    description: "Support x87 \"long double\""
    manual: true
    default: false

library:
  source-dirs: src
  other-modules:
  - Numeric.Rounded.Hardware.Internal.Rounding
  - Numeric.Rounded.Hardware.Internal.Class
  - Numeric.Rounded.Hardware.Internal.Constants
  - Numeric.Rounded.Hardware.Internal.Conversion
  - Numeric.Rounded.Hardware.Internal.RoundedResult
  - Numeric.Rounded.Hardware.Internal.Show
  - Numeric.Rounded.Hardware.Interval.ElementaryFunctions
  when:
  - condition: "!flag(pure-hs)"
    c-sources:
    - cbits/rounded.c
    cpp-options:
    - -DUSE_FFI
    exposed-modules:
    - Numeric.Rounded.Hardware.Backend.C
    other-modules:
    - FFIWrapper.Float
    - FFIWrapper.Double
  - condition: flag(c99)
    cc-options:
    - -DUSE_C99
  - condition: flag(avx512)
    cc-options:
    - -DUSE_AVX512
    - -mavx512f
  - condition: "!flag(pure-hs) && !flag(c99) && flag(ghc-prim) && arch(x86_64)"
    exposed-modules:
    - Numeric.Rounded.Hardware.Backend.FastFFI
    c-sources:
    - cbits/interval-prim-x86_64.s
    cpp-options:
    - -DUSE_GHC_PRIM
  - condition: flag(x87-long-double)
    dependencies: long-double
    c-sources:
    - cbits/rounded-x87longdouble.c
    exposed-modules:
    - Numeric.Rounded.Hardware.Backend.X87LongDouble
    cpp-options:
    - -DUSE_X87_LONG_DOUBLE
  dependencies:
  - tagged

tests:
  rounded-hw-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rounded-hw
    - hspec
    - QuickCheck
    when:
    - condition: flag(x87-long-double)
      dependencies: long-double
      other-modules:
      - X87LongDoubleSpec
      cpp-options:
      - -DTEST_X87_LONG_DOUBLE

  rounded-hw-doctests:
    main: doctests.hs
    dependencies:
    - doctest >= 0.8

benchmarks:
  rounded-hw-benchmark:
    main: Benchmark.hs
    source-dirs: benchmark
    dependencies:
    - rounded-hw
    - gauge
    - array
    - vector
