name:                rounded-hw
version:             0.1.0.0
github:              "minoki/rounded-hw"
license:             BSD3
author:              "ARATA Mizuki"
maintainer:          "minorinoki@gmail.com"
copyright:           "2019 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/minoki/rounded-hw#readme>

dependencies:
- base >= 4.7 && < 5
- integer-logarithms
- deepseq
- vector
- primitive
# - rounded

flags:
  pure-hs:
    description: Disable FFI
    manual: true
    default: false

  sse2:
    description: Use SSE2
    manual: true
    default: false

  ghc-prim:
    description: Use GHC foreign prim
    manual: true
    default: false

library:
  source-dirs: src
  other-modules:
  - Numeric.Rounded.Hardware.Base.Rounding
  - Numeric.Rounded.Hardware.Base.Class
  - Numeric.Rounded.Hardware.Base.Constants
  - Numeric.Rounded.Hardware.Base.Conversion
  - Numeric.Rounded.Hardware.Base.RoundedResult
  - Numeric.Rounded.Hardware.Base.Show
  - Numeric.Rounded.Hardware.Backend.Default
  when:
  - condition: "!flag(pure-hs)"
    c-sources:
    - cbits/rounded.c
    cpp-options:
    - -DUSE_FFI
    exposed-modules:
    - Numeric.Rounded.Hardware.Backend.C
    other-modules:
    - FFIImports
    - FFIWrapper.Float
    - FFIWrapper.Double
  - condition: flag(sse2)
    then:
      cpp-options:
      - -DUSE_SSE2
    else:
      cpp-options:
      - -DUSE_C99
  - condition: "!flag(pure-hs) && flag(ghc-prim) && arch(x86_64)"
    exposed-modules:
    - Numeric.Rounded.Hardware.Backend.FastFFI
    c-sources:
    - cbits/interval-prim-x86_64.s
    cpp-options:
    - -DUSE_GHC_PRIM
  dependencies:
  - tagged

tests:
  rounded-hw-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rounded-hw
    - hspec
    - QuickCheck

  rounded-hw-doctests:
    main: doctests.hs
    dependencies:
    - doctest >= 0.8

benchmarks:
  rounded-hw-benchmark:
    main: Benchmark.hs
    source-dirs: benchmark
    dependencies:
    - rounded-hw
    - gauge
    - array
    - vector
