name:                rounded-hw
version:             0.1.0.0
github:              "minoki/hs-rounded-hw"
license:             BSD3
author:              "ARATA Mizuki"
maintainer:          "minorinoki@gmail.com"
copyright:           "2019 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/minoki/hs-rounded-hw#readme>

dependencies:
- base >= 4.7 && < 5
- integer-logarithms
# - rounded

library:
  source-dirs: src
  c-sources:
  - cbits/rounded-c99.c
  - cbits/rounded-sse2.c

tests:
  rounded-hw-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rounded-hw
    - hspec
    - QuickCheck
